{"created": 1671367251.5784378, "duration": 0.07750177383422852, "exitcode": 2, "root": "/Users/seeul/section3", "environment": {"Python": "3.8.15", "Platform": "macOS-10.16-x86_64-i386-64bit", "Packages": {"pytest": "6.2.2", "pluggy": "0.13.1"}, "Plugins": {"json-report": "1.5.0", "submit": "1.3.3", "metadata": "2.0.4"}}, "summary": {"total": 0, "collected": 0}, "collectors": [{"nodeid": "", "outcome": "failed", "result": [], "longrepr": "/opt/anaconda3/envs/n312/lib/python3.8/importlib/__init__.py:127: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n<frozen importlib._bootstrap>:1014: in _gcd_import\n    ???\n<frozen importlib._bootstrap>:991: in _find_and_load\n    ???\n<frozen importlib._bootstrap>:975: in _find_and_load_unlocked\n    ???\n<frozen importlib._bootstrap>:671: in _load_unlocked\n    ???\n/opt/anaconda3/envs/n312/lib/python3.8/site-packages/_pytest/assertion/rewrite.py:170: in exec_module\n    exec(co, module.__dict__)\nds-sa-database/tests/Part_1/conftest.py:5: in <module>\n    from src import Part_1\nE   ModuleNotFoundError: No module named 'src'"}], "tests": []}